/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 7.0.10 */
public interface CalculatorTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTASSIGN = 2;
  public int JJTADD = 3;
  public int JJTSUB = 4;
  public int JJTMUL = 5;
  public int JJTDIV = 6;
  public int JJTTERM = 7;


  public String[] jjtNodeName = {
    "Expression",
    "void",
    "Assign",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Term",
  };
}
/* JavaCC - OriginalChecksum=6334394b05418e0392b36956d3a1900a (do not edit this line) */
