/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 7.0.10 */
public interface CalculatorTreeConstants
{
  public int JJTERROR_SKIPTO = 0;
  public int JJTEXPRESSION = 1;
  public int JJTVOID = 2;
  public int JJTADD = 3;
  public int JJTSUB = 4;
  public int JJTMUL = 5;
  public int JJTDIV = 6;
  public int JJTTERM = 7;


  public String[] jjtNodeName = {
    "error_skipto",
    "Expression",
    "void",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Term",
  };
}
/* JavaCC - OriginalChecksum=57ce492d7027bea4c19e5c9826a285e4 (do not edit this line) */
